exports.LOGIN_TYPE = {
  MOBILE_NUMBER: 1,
  GOOGLE: 2,
  QUICK: 3,
  APPLE: 4,
};

exports.WITHDRAWAL_STATUS = {
  PENDING: 1,
  ACCEPTED: 2,
  DECLINE: 3,
};

exports.HISTORY_TYPE = {
  DAILY_CHECK_IN_REWARD: 1,
  AD_VIEW_REWARD: 2,
  LOGIN_REWARD: 3,
  REFERRAL_REWARD: 4,
  COIN_PLAN_SUBSCRIPTION: 5,
  UNLOCK_VIDEO: 6,
  AUTO_UNLOCK_VIDEO: 7,
  VIP_PLAN_SUBSCRIPTION: 8,
  ADMIN_COIN_ADD: 9,
  ADMIN_COIN_DEDUCT: 10,
};

exports.CONTENT_TYPE = {
  MOVIE: 1,
  WEB_SERIES: 2,
};

exports.TYPE_OF_REPORT = {
  SHORT_VIDEO: 1,
};

exports.STATUS_OF_REPORT = {
  PENDING: 1,
  SOLVED: 2,
};
