const fs = require('fs');

const translations = {
  txtAppName: "247 Dramas",
  txtWhoops: "Ôi không!",
  txtNoInternetConnection: "Không có kết nối Internet",
  txtDescNoInternetConnection: "Vui lòng kiểm tra lại kết nối mạng của bạn.",
  txtTryAgain: "Thử lại",
  home: "Trang chủ",
  forYou: "Dành cho bạn",
  myList: "Danh sách của tôi",
  rewards: "Phần thưởng",
  profile: "Hồ sơ",
  myRewardCoin: "Xu thưởng của tôi",
  earnRewards: "Kiếm thưởng",
  convertCoin: "Đổi xu",
  withdrawToWallet: "Rút về ví",
  amount: "Số lượng",
  enterWithdrawalCoin: "Nhập số xu cần rút",
  withdrawCoin: "Rút xu",
  coin: "Xu",
  totalCoins: "Tổng xu",
  earnMore: "Kiếm thêm",
  referralReward: "Thưởng giới thiệu",
  go: "Đi",
  engagementRewards: "Thưởng tương tác",
  earned: "Đã kiếm",
  referralProgram: "Chương trình giới thiệu",
  referralProgramContent: "Nội dung chương trình",
  referralBonus: "Thưởng giới thiệu",
  numberOfMember: "Số lượng thành viên",
  earnCoins: "Kiếm xu",
  referralLink: "Liên kết giới thiệu",
  copiedOnClipboard: "Đã sao chép",
  referNow: "Giới thiệu ngay",
  referralHistory: "Lịch sử giới thiệu",
  youHaveCheckedInFor: "Bạn đã điểm danh",
  dayStraight: "ngày liên tiếp",
  today: "Hôm nay",
  checkIn: "Điểm danh",
  watchAds: "Xem quảng cáo",
  watchAd: "Xem quảng cáo",
  invitationCode: "Mã mời",
  myCoupons: "Mã giảm giá",
  feedback: "Phản hồi",
  language: "Ngôn ngữ",
  setting: "Cài đặt",
  termsOfService: "Điều khoản dịch vụ",
  privacyPolicy: "Chính sách bảo mật",
  deleteAccount: "Xóa tài khoản",
  rateUs: "Đánh giá chúng tôi",
  myWallet: "Ví của tôi",
  rewardCoin: "Xu thưởng",
  reFill: "Nạp xu",
  transactionHistory: "Lịch sử giao dịch",
  episodesUnlocked: "Tập đã mở khóa",
  episodesOnAutoUnlock: "Tự động mở khóa tập",
  rewardCoinsHistory: "Lịch sử xu thưởng",
  cancel: "Hủy",
  confirm: "Xác nhận",
  switchTo: "Chuyển sang",
  areYouSureWantToLogout: "Bạn có chắc chắn muốn đăng xuất không?",
  logout: "Đăng xuất",
  report: "Báo cáo",
  store: "Cửa hàng",
  restore: "Khôi phục",
  balance: "Số dư",
  coins: "Xu",
  price: "Giá",
  viewAll: "Xem tất cả",
  watchAdToUnlockForFree: "Xem quảng cáo để mở khóa miễn phí",
  watchedToday: "Đã xem hôm nay",
  unlockNow: "Mở khóa ngay",
  autoUnlockNextEpisode: "Tự động mở khóa tập tiếp theo",
  userHasBeeSuccessfullyDeleted: "Tài khoản đã được xóa thành công",
  newRelease: "Mới phát hành",
  attention: "Chú ý",
  iHaveReadAndAgreeToTheAboveContent: "Tôi đã đọc và đồng ý với nội dung trên",
  pleaseAgreeToTheAboveContentFirst: "Vui lòng đồng ý với nội dung trên trước",
  noResultsFound: "Không tìm thấy kết quả nào",
  searchHistory: "Lịch sử tìm kiếm",
  clearAll: "Xóa tất cả",
  peopleAreSearching: "Mọi người đang tìm kiếm",
  noVideosAvailable: "Không có video nào",
  youDontHaveAnyTransactionsYet: "Bạn chưa có giao dịch nào",
  youDontHaveAnyRewardCoinsHistoryYet: "Bạn chưa có lịch sử nhận xu",
  youDontHaveAnyEpisodesOnUnlockYet: "Bạn chưa mở khóa tập nào",
  youDontHaveAnyEpisodesOnAutoUnlockYet: "Chưa có tập nào tự động mở khóa",
  nohistoryYet: "Chưa có lịch sử",
  thatsAllForNow: "Đó là tất cả",
  play: "Phát",
  list: "Danh sách",
  share: "Chia sẻ",
  trailer: "Trailer",
  completed: "Đã hoàn thành",
  welcomeToStoryBox: "Chào mừng bạn đến với ứng dụng",
  continueWithGuest: "Tiếp tục với tư cách Khách",
  signInWithGoogle: "Đăng nhập bằng Google",
  continueWithApple: "Tiếp tục bằng Apple",
  ifYouContinueYouAgree: "Nếu bạn tiếp tục, bạn đồng ý với",
  history: "Lịch sử",
  nothingHereYet: "Chưa có gì ở đây",
  episode: "Tập",
  dailyCheckInReward: "Thưởng điểm danh hàng ngày",
  asViewReward: "Thưởng xem quảng cáo",
  loginReward: "Thưởng đăng nhập",
  coinPlanSubscription: "Gói xu nạp",
  unlockVideo: "Mở khóa video",
  autoUnlockVideo: "Tự động mở khóa video",
  details: "Chi tiết",
  monthlyVIP: "VIP Hàng tháng",
  yearlyVIP: "VIP Hàng năm",
  weeklyVIP: "VIP Hàng tuần",
  unlockAllSeriesFor: "Mở khóa tất cả series trong",
  days: "ngày",
  youAreReportingTheBillionaire: "Bạn đang báo cáo",
  reasonForReporting: "Lý do báo cáo",
  pleaseEnterAReasonForReporting: "Vui lòng chọn một lý do",
  emailAddress: "Địa chỉ Email",
  optionalPleaseEnterSoWeCanContactYou: "(Tùy chọn) Vui lòng điền để chúng tôi có thể liên hệ",
  submit: "Gửi",
  searchByTitleTheme: "Tìm kiếm theo tên phim...",
  signOut: "Đăng xuất",
  rateThisApp: "Đánh giá ứng dụng này",
  ifYouLikeThisApp: "Nếu bạn thích ứng dụng này, hãy dành chút thời gian để đánh giá.",
  rate: "Đánh giá",
  noThanks: "Không, cảm ơn",
  maybeLater: "Để sau",
  mostTrending: "Thịnh hành nhất",
  noImage: "Không có ảnh",
  continueWatching: "Tiếp tục xem",
  more: "Thêm",
  newText: "Mới",
  comingSoon: "Sắp ra mắt",
  mySubscription: "Gói đăng ký của tôi",
  dateOfPurchase: "Ngày mua",
  planDuration: "Thời hạn gói",
  selectPaymentOption: "Chọn phương thức thanh toán",
  stripe: "Stripe",
  inAppPurchase: "In-App Purchase",
  applePurchase: "Apple Purchase",
  razorPay: "RazorPay",
  flutterWave: "FlutterWave",
  payPal: "PayPal",
  payStack: "PayStack",
  cashFree: "CashFree",
  nothingHereYetTxt: "Chưa có gì ở đây",
  yourMaxAdLimitIsReachedForToday: "Đã đạt giới hạn xem quảng cáo hôm nay",
  txtMostSearched: "Tìm kiếm nhiều nhất",
  txtReport: "Báo cáo",
  txtCancel: "Hủy",
  txtExit: "Thoát",
  txtExitApp: "Thoát ứng dụng",
  txtItIsSpam: "Đây là thư rác",
  txtNudityOrSexualActivity: "Khỏa thân hoặc hoạt động tình dục",
  txtHateSpeechOrSymbols: "Ngôn từ hoặc biểu tượng thù ghét",
  txtViolenceOrDangerousOrganization: "Bạo lực hoặc tổ chức nguy hiểm",
  txtFalseInformation: "Thông tin sai lệch",
  txtBullyingOrHarassment: "Bắt nạt hoặc quấy rối",
  txtScamOrFraud: "Lừa đảo",
  txtIntellectualPropertyViolation: "Vi phạm sở hữu trí tuệ",
  txtSuicideOrSelfInjury: "Tự tử hoặc tự gây thương tích",
  txtDrugs: "Ma túy",
  txtEatingDisorders: "Rối loạn ăn uống",
  txtSomethingElse: "Lý do khác",
  txtChildAbuse: "Lạm dụng trẻ em",
  txtOthers: "Khác",
  txtReportSending: "Đang gửi báo cáo...",
  txtReportSendSuccess: "Báo cáo đã gửi thành công",
  txtExplore: "Khám phá",
  txtNew: "Mới",
  txtCategories: "Thể loại",
  txtRanking: "Xếp hạng",
  txtRecommendedForYou: "Đề xuất cho bạn",
  txtWatchFullDrama: "Xem toàn bộ drama",
  txtApplyFilter: "Áp dụng bộ lọc",
  txtSubscribeNow: "Đăng ký ngay",
  txtMyCurrentBalance: "Số dư hiện tại",
  txtMobileNumHintTest: "Nhập số điện thoại",
  txtWatchAllForFree: "Xem miễn phí tất cả",
  txtAdFree: "Không quảng cáo",
  txtEnjoyExclusiveBenefits: "Tận hưởng lợi ích độc quyền",
  txtVIP: "VIP",
  txtActivate: "Kích hoạt",
  txtActivated: "Đã kích hoạt",
  txtOrLoginUsingAnotherMethod: "Hoặc đăng nhập bằng phương thức khác",
  txtPleaseEnterMobileNumber: "Vui lòng nhập số điện thoại",
  txtNewOTPHasBeenSentToYourPhone: "Mã OTP đã được gửi đến điện thoại",
  txtYouAreNotAVipYet: "Bạn chưa phải là VIP",
  txtPleaseEnterCorrectMobileNumber: "Vui lòng nhập số điện thoại hợp lệ",
  txtVerificationCodeSend: "Đã gửi mã xác minh",
  txtVerificationTimeout: "Hết thời gian xác minh",
  txtPleaseEnterVerificationCode: "Vui lòng nhập mã xác minh",
  txtPleaseEnterNumber: "Vui lòng nhập số",
  txtSuccessfullySubscribedToPlan: "Đã đăng ký gói thành công",
  txtFailedToSubscribeToPlan: "Đăng ký gói thất bại",
  txtChooseYourPlan: "Chọn gói của bạn",
  txtUnlockPremiumFeatures: "Mở khóa các tính năng Premium",
  txtGetAccessToAllPremiumFeaturesAndEnjoyUnlimitedUsage: "Truy cập mọi tính năng Premium và sử dụng không giới hạn",
  txtSelectAPlan: "Chọn một gói",
  txtSubscribeTo: "Đăng ký vào",
  txtBySubscribingYouAgreeToOurTermsOfServiceAndPrivacyPolicy: "Bằng cách đăng ký, bạn đồng ý với Điều khoản dịch vụ và Chính sách bảo mật.",
  toastPleaseCheckYourInternetConnection: "Vui lòng kiểm tra kết nối internet",
  txtSomeThingWentWrong: "Đã có lỗi xảy ra",
  txtWatchWithCoin: "Xem bằng Xu",
  txtVerificationFailedDueToMultipleAttempts: "Xác minh thất bại do nhiều lần thử",
  txtMySubscription: "Gói đăng ký của tôi",
  txtUnlockAllEpisodesForWeek: "Mở khóa mọi tập trong tuần",
  txtAutoRenewal: "Tự động gia hạn",
  txtCancelAnytime: "Hủy bất cứ lúc nào",
  txtTips: "Mẹo nhỏ",
  txtThisUser: "Người dùng này",
  txtBlockedByAdmin: "Đã bị khóa bởi Admin",
  txtCloseApp: "Đóng ứng dụng",
  txtSortBy: "Sắp xếp theo",
  txtReset: "Đặt lại",
  txtPleaseSelectAtLeastOneCategory: "Vui lòng chọn ít nhất một thể loại",
  txtConfirm: "Xác nhận",
  txtPleaseSelectACoinPlanFirst: "Vui lòng chọn một gói Xu trước",
  txtFlutterWavePaymentFailed: "Thanh toán FlutterWave thất bại",
  txtProductKeyNotFoundForThisPlan: "Không tìm thấy Product Key cho gói này",
  txtFailedToStartPurchase: "Không thể bắt đầu thanh toán",
  txtPaymentError: "Lỗi thanh toán",
  txtAreYouSureYouWantToExitTheApp: "Bạn có chắc chắn muốn thoát ứng dụng?",
  txtNoMoreVideos: "Không còn video nào",
  txtCheckInSuccessful: "Điểm danh thành công",
  txtFilterData: "Lọc dữ liệu",
  txtLoginFailedPleaseTryAgain: "Đăng nhập thất bại, vui lòng thử lại",
  txtPleaseEnterValidNumber: "Vui lòng nhập số hợp lệ",
  txtAnErrorOccurredDuringLogin: "Đã xảy ra lỗi trong khi đăng nhập",
  txtAppleLogin: "Đăng nhập Apple",
  txtGoogleLogin: "Đăng nhập Google",
  txtSignInWithGoogle: "Đăng nhập với Google",
  txtOTPSentTo: "OTP đã được gửi đến",
  txtKindlyWait: "Vui lòng chờ",
  txtToResend: "để gửi lại",
  txtKindlyTapResendOTPToResend: "Vui lòng nhấn Gửi lại OTP để nhận lại mã",
  txtResendOTP: "Gửi lại OTP",
  txtVerifyOTP: "Xác minh OTP",
  txtPaymentSuccessfully: "Thanh toán thành công",
  txtAutoScroll: "Tự động cuộn",
  txtUpdateAvailable: "Có bản cập nhật mới",
  txtWeHaveMadeImprovementsToEnhanceYourExperienceUpdateNowToAccessTheLatestFeatures: "Chúng tôi đã cải tiến ứng dụng. Vui lòng cập nhật để trải nghiệm tính năng mới nhất.",
  txtRequiredForContinuedAccess: "Yêu cầu bắt buộc để tiếp tục sử dụng",
  txtUserDoesNotFound: "Không tìm thấy người dùng",
  txtUpdateNow: "Cập nhật ngay",
  txtCoins: "Xu",
  txtTip1: "Mẹo 1",
  txtTip2: "Mẹo 2",
  txtTip3: "Mẹo 3",
  txtTip4: "Mẹo 4",
  txtTip5: "Mẹo 5",
  txtTip6: "Mẹo 6",
  txtTip7: "Mẹo 7",
  txtTip8: "Mẹo 8",
  txtTip9: "Mẹo 9",
  txtVipPlanSubscription: "Đăng ký gói VIP",
  txtAddCoinByAdmin: "Thêm xu bởi Admin",
  txtDeductCoinByAdmin: "Trừ xu bởi Admin",
  txtBuyCoinsHistory: "Lịch sử mua xu",
  buyTransactionHistory: "Lịch sử giao dịch mua"
};

let csvContent = "KEY,MODULE,vi\n";
for (const key of Object.keys(translations)) {
  const value = `"${translations[key].replace(/"/g, '""')}"`;
  csvContent += `${key},app,${value}\n`;
}

fs.writeFileSync('translations_vi.csv', csvContent);
console.log("CSV created: translations_vi.csv");
