const fs = require('fs');
const { parse } = require('csv-parse/sync');

// Read the existing Vietnamese CSV
const viCsvPath = '/Users/baonguyen/StoryBox all file/Source Code/admin/backend/translations_vi.csv';
const viDataRaw = fs.readFileSync(viCsvPath, 'utf8');
const viRecords = parse(viDataRaw, { columns: true, skip_empty_lines: true });

// The English translations
const translationsEn = {
  txtAppName: "247 Dramas",
  txtWhoops: "Whoops!",
  txtNoInternetConnection: "No Internet Connection",
  txtDescNoInternetConnection: "Please check your network connection.",
  txtTryAgain: "Try Again",
  home: "Home",
  forYou: "For You",
  myList: "My List",
  rewards: "Rewards",
  profile: "Profile",
  myRewardCoin: "My Reward Coin",
  earnRewards: "Earn Rewards",
  convertCoin: "Convert Coin",
  withdrawToWallet: "Withdraw to Wallet",
  amount: "Amount",
  enterWithdrawalCoin: "Enter withdrawal coin",
  withdrawCoin: "Withdraw Coin",
  coin: "Coin",
  totalCoins: "Total Coins",
  earnMore: "Earn More",
  referralReward: "Referral Reward",
  go: "Go",
  engagementRewards: "Engagement Rewards",
  earned: "Earned",
  referralProgram: "Referral Program",
  referralProgramContent: "Referral Program Content",
  referralBonus: "Referral Bonus",
  numberOfMember: "Number of Members",
  earnCoins: "Earn Coins",
  referralLink: "Referral Link",
  copiedOnClipboard: "Copied to clipboard",
  referNow: "Refer Now",
  referralHistory: "Referral History",
  youHaveCheckedInFor: "You have checked in for",
  dayStraight: "day(s) straight",
  today: "Today",
  checkIn: "Check-in",
  watchAds: "Watch Ads",
  watchAd: "Watch Ad",
  invitationCode: "Invitation Code",
  myCoupons: "My Coupons",
  feedback: "Feedback",
  language: "Language",
  setting: "Setting",
  termsOfService: "Terms of Service",
  privacyPolicy: "Privacy Policy",
  deleteAccount: "Delete Account",
  rateUs: "Rate Us",
  myWallet: "My Wallet",
  rewardCoin: "Reward Coin",
  reFill: "Refill",
  transactionHistory: "Transaction History",
  episodesUnlocked: "Episodes Unlocked",
  episodesOnAutoUnlock: "Episodes on Auto-Unlock",
  rewardCoinsHistory: "Reward Coins History",
  cancel: "Cancel",
  confirm: "Confirm",
  switchTo: "Switch to",
  areYouSureWantToLogout: "Are you sure you want to logout?",
  logout: "Logout",
  report: "Report",
  store: "Store",
  restore: "Restore",
  balance: "Balance",
  coins: "Coins",
  price: "Price",
  viewAll: "View All",
  watchAdToUnlockForFree: "Watch ad to unlock for free",
  watchedToday: "Watched today",
  unlockNow: "Unlock Now",
  autoUnlockNextEpisode: "Auto-unlock next episode",
  userHasBeeSuccessfullyDeleted: "User has been successfully deleted",
  newRelease: "New Release",
  attention: "Attention",
  iHaveReadAndAgreeToTheAboveContent: "I have read and agree to the above content",
  pleaseAgreeToTheAboveContentFirst: "Please agree to the above content first",
  noResultsFound: "No results found",
  searchHistory: "Search History",
  clearAll: "Clear All",
  peopleAreSearching: "People are searching",
  noVideosAvailable: "No videos available",
  youDontHaveAnyTransactionsYet: "You don't have any transactions yet",
  youDontHaveAnyRewardCoinsHistoryYet: "You don't have any reward coins history yet",
  youDontHaveAnyEpisodesOnUnlockYet: "You don't have any episodes unlocked yet",
  youDontHaveAnyEpisodesOnAutoUnlockYet: "You don't have any episodes on auto-unlock yet",
  nohistoryYet: "No history yet",
  thatsAllForNow: "That's all for now",
  play: "Play",
  list: "List",
  share: "Share",
  trailer: "Trailer",
  completed: "Completed",
  welcomeToStoryBox: "Welcome to 247 Dramas",
  continueWithGuest: "Continue with Guest",
  signInWithGoogle: "Sign In with Google",
  continueWithApple: "Continue with Apple",
  ifYouContinueYouAgree: "If you continue, you agree to",
  history: "History",
  nothingHereYet: "Nothing here yet",
  episode: "Episode",
  dailyCheckInReward: "Daily Check-in Reward",
  asViewReward: "Ad View Reward",
  loginReward: "Login Reward",
  coinPlanSubscription: "Coin Plan Subscription",
  unlockVideo: "Unlock Video",
  autoUnlockVideo: "Auto-unlock Video",
  details: "Details",
  monthlyVIP: "Monthly VIP",
  yearlyVIP: "Yearly VIP",
  weeklyVIP: "Weekly VIP",
  unlockAllSeriesFor: "Unlock all series for",
  days: "days",
  youAreReportingTheBillionaire: "You are reporting",
  reasonForReporting: "Reason for reporting",
  pleaseEnterAReasonForReporting: "Please select a reason for reporting",
  emailAddress: "Email Address",
  optionalPleaseEnterSoWeCanContactYou: "(Optional) Please enter so we can contact you",
  submit: "Submit",
  searchByTitleTheme: "Search by title...",
  signOut: "Sign Out",
  rateThisApp: "Rate this app",
  ifYouLikeThisApp: "If you like this app, please take a moment to rate it.",
  rate: "Rate",
  noThanks: "No thanks",
  maybeLater: "Maybe later",
  mostTrending: "Most Trending",
  noImage: "No image",
  continueWatching: "Continue Watching",
  more: "More",
  newText: "New",
  comingSoon: "Coming Soon",
  mySubscription: "My Subscription",
  dateOfPurchase: "Date of Purchase",
  planDuration: "Plan Duration",
  selectPaymentOption: "Select Payment Option",
  stripe: "Stripe",
  inAppPurchase: "In-App Purchase",
  applePurchase: "Apple Purchase",
  razorPay: "RazorPay",
  flutterWave: "FlutterWave",
  payPal: "PayPal",
  payStack: "PayStack",
  cashFree: "CashFree",
  nothingHereYetTxt: "Nothing here yet",
  yourMaxAdLimitIsReachedForToday: "Your maximum ad limit is reached for today",
  txtMostSearched: "Most Searched",
  txtReport: "Report",
  txtCancel: "Cancel",
  txtExit: "Exit",
  txtExitApp: "Exit App",
  txtItIsSpam: "It is spam",
  txtNudityOrSexualActivity: "Nudity or sexual activity",
  txtHateSpeechOrSymbols: "Hate speech or symbols",
  txtViolenceOrDangerousOrganization: "Violence or dangerous organization",
  txtFalseInformation: "False information",
  txtBullyingOrHarassment: "Bullying or harassment",
  txtScamOrFraud: "Scam or fraud",
  txtIntellectualPropertyViolation: "Intellectual property violation",
  txtSuicideOrSelfInjury: "Suicide or self-injury",
  txtDrugs: "Drugs",
  txtEatingDisorders: "Eating disorders",
  txtSomethingElse: "Something else",
  txtChildAbuse: "Child abuse",
  txtOthers: "Others",
  txtReportSending: "Sending report...",
  txtReportSendSuccess: "Report sent successfully",
  txtExplore: "Explore",
  txtNew: "New",
  txtCategories: "Categories",
  txtRanking: "Ranking",
  txtRecommendedForYou: "Recommended for You",
  txtWatchFullDrama: "Watch full drama",
  txtApplyFilter: "Apply Filter",
  txtSubscribeNow: "Subscribe Now",
  txtMyCurrentBalance: "My Current Balance",
  txtMobileNumHintTest: "Enter mobile number",
  txtWatchAllForFree: "Watch all for free",
  txtAdFree: "Ad-free",
  txtEnjoyExclusiveBenefits: "Enjoy exclusive benefits",
  txtVIP: "VIP",
  txtActivate: "Activate",
  txtActivated: "Activated",
  txtOrLoginUsingAnotherMethod: "Or login using another method",
  txtPleaseEnterMobileNumber: "Please enter mobile number",
  txtNewOTPHasBeenSentToYourPhone: "New OTP has been sent to your phone",
  txtYouAreNotAVipYet: "You are not a VIP yet",
  txtPleaseEnterCorrectMobileNumber: "Please enter correct mobile number",
  txtVerificationCodeSend: "Verification code sent",
  txtVerificationTimeout: "Verification timeout",
  txtPleaseEnterVerificationCode: "Please enter verification code",
  txtPleaseEnterNumber: "Please enter number",
  txtSuccessfullySubscribedToPlan: "Successfully subscribed to plan",
  txtFailedToSubscribeToPlan: "Failed to subscribe to plan",
  txtChooseYourPlan: "Choose your plan",
  txtUnlockPremiumFeatures: "Unlock premium features",
  txtGetAccessToAllPremiumFeaturesAndEnjoyUnlimitedUsage: "Get access to all premium features and enjoy unlimited usage",
  txtSelectAPlan: "Select a plan",
  txtSubscribeTo: "Subscribe to",
  txtBySubscribingYouAgreeToOurTermsOfServiceAndPrivacyPolicy: "By subscribing you agree to our Terms of Service and Privacy Policy.",
  toastPleaseCheckYourInternetConnection: "Please check your internet connection",
  txtSomeThingWentWrong: "Something went wrong",
  txtWatchWithCoin: "Watch with Coin",
  txtVerificationFailedDueToMultipleAttempts: "Verification failed due to multiple attempts",
  txtMySubscription: "My Subscription",
  txtUnlockAllEpisodesForWeek: "Unlock all episodes for the week",
  txtAutoRenewal: "Auto-renewal",
  txtCancelAnytime: "Cancel anytime",
  txtTips: "Tips",
  txtThisUser: "This user",
  txtBlockedByAdmin: "Blocked by Admin",
  txtCloseApp: "Close App",
  txtSortBy: "Sort by",
  txtReset: "Reset",
  txtPleaseSelectAtLeastOneCategory: "Please select at least one category",
  txtConfirm: "Confirm",
  txtPleaseSelectACoinPlanFirst: "Please select a Coin Plan first",
  txtFlutterWavePaymentFailed: "FlutterWave payment failed",
  txtProductKeyNotFoundForThisPlan: "Product key not found for this plan",
  txtFailedToStartPurchase: "Failed to start purchase",
  txtPaymentError: "Payment error",
  txtAreYouSureYouWantToExitTheApp: "Are you sure you want to exit the app?",
  txtNoMoreVideos: "No more videos",
  txtCheckInSuccessful: "Check-in successful",
  txtFilterData: "Filter data",
  txtLoginFailedPleaseTryAgain: "Login failed, please try again",
  txtPleaseEnterValidNumber: "Please enter valid number",
  txtAnErrorOccurredDuringLogin: "An error occurred during login",
  txtAppleLogin: "Apple Login",
  txtGoogleLogin: "Google Login",
  txtSignInWithGoogle: "Sign In with Google",
  txtOTPSentTo: "OTP sent to",
  txtKindlyWait: "Kindly wait",
  txtToResend: "to resend",
  txtKindlyTapResendOTPToResend: "Kindly tap Resend OTP to resend",
  txtResendOTP: "Resend OTP",
  txtVerifyOTP: "Verify OTP",
  txtPaymentSuccessfully: "Payment successfully",
  txtAutoScroll: "Auto-scroll",
  txtUpdateAvailable: "Update available",
  txtWeHaveMadeImprovementsToEnhanceYourExperienceUpdateNowToAccessTheLatestFeatures: "We have made improvements. Update now to access the latest features.",
  txtRequiredForContinuedAccess: "Required for continued access",
  txtUserDoesNotFound: "User does not found",
  txtUpdateNow: "Update Now",
  txtCoins: "Coins",
  txtTip1: "Tip 1",
  txtTip2: "Tip 2",
  txtTip3: "Tip 3",
  txtTip4: "Tip 4",
  txtTip5: "Tip 5",
  txtTip6: "Tip 6",
  txtTip7: "Tip 7",
  txtTip8: "Tip 8",
  txtTip9: "Tip 9",
  txtVipPlanSubscription: "VIP Plan Subscription",
  txtAddCoinByAdmin: "Add coin by Admin",
  txtDeductCoinByAdmin: "Deduct coin by Admin",
  txtBuyCoinsHistory: "Buy coins history",
  buyTransactionHistory: "Buy transaction history"
};

let csvContent = "KEY,MODULE,vi,en\n";

for (const row of viRecords) {
  const key = row.KEY;
  const moduleName = row.MODULE;
  const viValue = `"${(row.vi || "").replace(/"/g, '""')}"`;
  
  let enText = translationsEn[key] || key;
  const enValue = `"${enText.replace(/"/g, '""')}"`;

  csvContent += `${key},${moduleName},${viValue},${enValue}\n`;
}

fs.writeFileSync('/Users/baonguyen/.gemini/antigravity-ide/brain/ab8d0e0e-6935-4cc7-9504-e74ba5b83089/scratch/translations_full.csv', csvContent);
console.log("Full CSV created: translations_full.csv");
